BEGIN;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS unit_base VARCHAR(10) NOT NULL DEFAULT 'pza',
    ADD COLUMN IF NOT EXISTS product_type VARCHAR(20) NOT NULL DEFAULT 'PIEZA',
    ADD COLUMN IF NOT EXISTS pack_factor NUMERIC(14,3),
    ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(8,4) NOT NULL DEFAULT 0.16,
    ADD COLUMN IF NOT EXISTS remate_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS remate_type VARCHAR(20),
    ADD COLUMN IF NOT EXISTS remate_value NUMERIC(14,2),
    ADD COLUMN IF NOT EXISTS remate_start_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS remate_end_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS remate_marked_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS remate_marked_by UUID REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE sales
    ADD COLUMN IF NOT EXISTS local_reference VARCHAR(120),
    ADD COLUMN IF NOT EXISTS amount_received NUMERIC(14,2),
    ADD COLUMN IF NOT EXISTS change_amount NUMERIC(14,2),
    ADD COLUMN IF NOT EXISTS fiscal_data JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMIT;
